---
title: "pregled"
author: "1349136962 FILIP MIŠKOVIĆ"
date: "2024-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
hotel <- read_csv("../data/Hotel bookings/hotel_bookings.csv")
hotel

# Ako nemate numerički ekvivalent za sve mjesece, možete koristiti ovu mapu
month_mapping <- c("January" = 1, "February" = 2, "March" = 3, "April" = 4, "May" = 5, "June" = 6, "July" = 7, "August" = 8, "September" = 9, "October" = 10, "November" = 11, "December" = 12)

# Koristite funkciju match da biste dobili numeričke ekvivalente
hotel$arrival_date_month <- match(hotel$arrival_date_month, names(month_mapping))

hotel$arrival_date <- as.Date(paste(hotel$arrival_date_year, hotel$arrival_date_month, hotel$arrival_date_day_of_month, sep = "-"))

hotel$arrival_date_year <- NULL
hotel$arrival_date_month <- NULL
hotel$arrival_date_day_of_month <- NULL

hotel$reservation_status_date <- as.Date(hotel$reservation_status_date, format = "%d-%m-%y")

glimpse(hotel)

sum(hotel$is_repeated_guest)
unique(hotel$is_repeated_guest)
table(hotel$days_in_waiting_list)

#proba

hotel

```
```{r}
#Altea 

#1.Dolaze li više ljudi s djecom ili bez djece?

#(moguće je imati 0 children, a 1 babies) <- pazi
#sDjecom je zbroj children i babies
#moguce je imati 0 odraslih, a != 0 djece <- zanemari
glimpse(hotel)

bezDjece <- hotel[(hotel$adults > 0) & (hotel$children==0) & (hotel$babies==0), ]
sDjecom <- hotel[(hotel$adults > 0) & ((hotel$children>0) | (hotel$babies>0)), ]
samoDjeca <- hotel[(hotel$adults == 0) & (hotel$children>0), ] #spomeni kao zanimljivost

#ggplot() +
#  geom_bar(data = sDjecom, aes(x = "Odrasli s djecom", fill = "Odrasli s djecom")) +
#  geom_bar(data = bezDjece, aes(x = "Odrasli bez djece", fill ="Odrasli bez djece")) +
#  labs(title = "Analiza gostiju - dolasci s djecom/bez djece", x=NULL, y=NULL) +
#  scale_fill_brewer(palette = "Set1", name=NULL) + theme_minimal()

#sum(((hotel$children != 0) | (hotel$babies != 0)) & hotel$adults>0, na.rm=T) #9109 dolaze s djecom
#sum((hotel$children == 0) & (hotel$babies == 0) & (hotel$adults>0), na.rm=T) #109874 dolaze bez djece
#sum(hotel$adults==0 & (hotel$babies>0 | hotel$children>0), na.rm=T) #223 ???

table(hotel$adults)
hotel[hotel$adults == 0 & hotel$is_canceled==0 & (hotel$babies>0 | hotel$children>0), ]

#rade pie chart!
dff2 <- data.frame(group = c("Odrasli s djecom", "Odrasli"), 
      value=c(nrow(sDjecom), nrow(bezDjece)))
dff2

ggplot(dff2, aes(x="", y=value, fill=group)) +
  geom_bar(stat ="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(round(value/nrow(hotel),2)*100, "%")), position = position_stack(vjust=0.5)) +
  labs(title = "Analiza gostiju - dolasci s djecom/bez djece", x=NULL, y=NULL) +
  scale_fill_brewer(palette="Set2", name="Gosti")



#mozda je bolje zbrojiti ljude s djecom i s dojenčadi pa samo u opisu staviti među kojima su i
#oni s dojenčadi...

  


#2.Tip sobe za goste s djecom ili bez? Filip ima općenito pa izdvoji samo ove s djecom

table(sDjecom$reserved_room_type)

sDjecom2 <- sDjecom[!is.na(sDjecom$reserved_room_type), ]
  
ggplot(sDjecom2, aes(x = "", fill = reserved_room_type)) +
  geom_bar(color = "white", position = "fill") +
  labs(x = NULL, title="Analiza gostiju - tip sobe za goste s djecom", y=NULL) +
  scale_fill_brewer(name="Tip sobe", palette = "Set2")

table(hotel$reserved_room_type)
table(sDjecom2$reserved_room_type) #L i P nema


#3.Koji gosti dolaze više autima (s djecom ili bez)?

#sDjecomAutom <- hotel[hotel$adults>0 & ((hotel$children >0) | (hotel$babies>0)) & hotel$required_car_parking_spaces>0, ]

#bezDjeceAutom <- hotel[hotel$adults>0 & ((hotel$children ==0) & (hotel$babies==0)) & hotel$required_car_parking_spaces>00, ]

#ggplot() + 
#  geom_bar(data=bezDjeceAutom, aes(x="Dolazak autom bez djece",fill="Dolazak autom bez #"djece")) +
#  geom_bar(data=sDjecomAutom, aes(x="Dolazak autom s djecom", fill="Dolazak autom s djecom")) +
#  labs(title = "Analiza gostiju - dolasci s djecom/bez djece autom", x=NULL, y=NULL) +
#  scale_fill_brewer(palette = "Set1", name=NULL) +
#  scale_y_continuous(name="rezervacije")

#izmjena: opcenito potraznja za parking mjestom - ima vise smisla
trebaParking <- hotel[hotel$required_car_parking_spaces != 0, ]
neTrebaParking <- hotel[hotel$required_car_parking_spaces == 0, ]

#ggplot() + geom_bar(data=trebaParking, aes(x="Dolazak autom", fill="Dolazak autom")) +
#  geom_bar(data=neTrebaParking, aes(x="Nije potrebno parkirno mjesto", fill="Nije potrebno parkirno mjesto")) +
#  labs(title = "Analiza gostiju - potreba za parkirnim mjestom", x=NULL, y=NULL) +
#  scale_fill_brewer(palette = "Set1", name=NULL) +
#  scale_y_continuous(name="rezervacije")

#ovdje!!

dff <- data.frame(group = c("Potreban parking", "Nije potreban parking"), 
      value=c(nrow(trebaParking), nrow(neTrebaParking)))

ggplot(dff, aes(x="", y=value, fill=group)) +
  geom_bar(stat ="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(round(value/nrow(hotel),2)*100, "%")), position = position_stack(vjust=0.5)) +
  labs(title = "Analiza gostiju - potreba za parkirnim mjestom", x=NULL, y=NULL) +
  scale_fill_brewer(palette="Set2", name="Parking")
  
  
  table(hotel$required_car_parking_spaces)
  hotel[hotel$required_car_parking_spaces==8, ] # od kojih 1,2,3,8
  nrow(hotel)


#4.Analiziranje prosječnog vremena boravka gostiju.

pom <- hotel$stays_in_weekend_nights + hotel$stays_in_week_nights
prosjecno_vrijeme_boravka <- mean(pom)
prosjecno_vrijeme_boravka #3.4279

#stavi za sve ljude koliko dugo budu pa to iskaži nekako, gledam po nocenjima
hotel$ukupno_nocenja <- hotel$stays_in_weekend_nights + hotel$stays_in_week_nights
hotel

table(hotel$ukupno_nocenja) #min 0, max 69

ggplot(hotel, aes(x=as.factor(ukupno_nocenja))) + geom_bar() +
  scale_y_log10(name="rezervacije") +
  labs(title="Analiza gostiju - raspodjela broja noćenja", x="broj noćenja")

#na x osi predstavljene su sve vrijednosti bookinarnih noćenja, kako ide od 1 ovi koji nemaju
#pripadni bar su 1


```

```{r}
# Filipove škrabotine

# Koliko ranije gost rezervira smještaj?
hotel
lead_time <- data.frame(NumOfDays = as.numeric(names(table(hotel$lead_time))), Frequency = as.numeric(table(hotel$lead_time)))
lead_time
ggplot(lead_time, aes(x = NumOfDays, y = Frequency)) + 
  geom_freqpoly(stat = "identity") +
  labs(title = "Vrijeme rezerviranja prije dolaska", x = "Broj dana", y = "Broj gostiju")



# Koliko često gosti otkazuju rezervaciju?
hotel[hotel$is_canceled == 1, ]
canceled <- hotel[hotel$reservation_status == "Canceled", ]
canceled
checkOut <- hotel[hotel$reservation_status == "Check-Out", ]
checkOut
noShow <- hotel[hotel$reservation_status == "No-Show", ]
noShow

reservation_status_PC <- data.frame(group = c("Otkazano", "Odlazak", "Nedolazak"), 
      value=c(nrow(canceled), nrow(checkOut), nrow(noShow)))
reservation_status_PC

ggplot(reservation_status_PC, aes(x = "", y = value, fill = group)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(round(value/nrow(hotel), 2) * 100, "%")), position = position_stack(vjust = 0.5)) +
  labs(title = "Analiza rezervacija - odnos među statusima rezervacija", x = NULL, y = NULL) +
  scale_fill_brewer(palette = "Set2", name = "Status rezervacije")


# Identifikacija najpopularnijih tipova soba ili paketa.
# ima 10 tipova soba!
table(hotel$reserved_room_type)

tipA <- hotel[hotel$reserved_room_type == "A", ]
tipB <- hotel[hotel$reserved_room_type == "B", ]
tipC <- hotel[hotel$reserved_room_type == "C", ]
tipD <- hotel[hotel$reserved_room_type == "D", ]
tipE <- hotel[hotel$reserved_room_type == "E", ]
tipF <- hotel[hotel$reserved_room_type == "F", ]
tipG <- hotel[hotel$reserved_room_type == "G", ]
tipH <- hotel[hotel$reserved_room_type == "H", ]
tipL <- hotel[hotel$reserved_room_type == "L", ]
tipP <- hotel[hotel$reserved_room_type == "P", ]

nrow(tipA) + nrow(tipB) + nrow(tipC) + nrow(tipD) + nrow(tipE) + nrow(tipF) + nrow(tipG) + nrow(tipH) + nrow(tipL) + nrow(tipP)

tipovi_soba_PC <- data.frame(group = c("A", "B", "C", "D", "E", "F", "G", "H", "L", "P"), 
                             value = c(nrow(tipA), nrow(tipB), nrow(tipC), nrow(tipD), nrow(tipE), nrow(tipF), nrow(tipG), nrow(tipH), nrow(tipL), nrow(tipP)))

# postoji 5 soba kojima je postotak zastupljenosti veći od 1% pa ćemo uzeti te, ostale ćemo samo u izvještaju nabrojati da postoje i da je njihova zastupljenost manja od 1%
sorted_tipovi_soba_PC <- arrange(tipovi_soba_PC, desc(value))
sorted_tipovi_soba_PC
lapply(sorted_tipovi_soba_PC$value, function(x) {
  x / nrow(hotel) * 100
}) %>% unlist


reduced_tipovi_soba_PC <- sorted_tipovi_soba_PC[sorted_tipovi_soba_PC$value / nrow(hotel) * 100 >= 1, ]
reduced_tipovi_soba_PC

ggplot(reduced_tipovi_soba_PC, aes(x = "", y = value, fill = group)) +
  geom_bar(stat = "identity", width = 1) + 
  #coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(round(value / nrow(hotel), 2) * 100, "%")), position = position_stack(vjust = 0.5)) +
  labs(title = "Najpopularnije sobe", x = NULL, y = NULL) +
  scale_fill_brewer(palette = "Set2", name = "Tip sobe")


# Odnos ispunjenih i neispunjenih zahtjeva gostiju
ispunjeniZahtjevi <- hotel[hotel$reserved_room_type == hotel$assigned_room_type, ]
ispunjeniZahtjevi
neispunjeniZahtjevi <- hotel[hotel$reserved_room_type != hotel$assigned_room_type, ]
neispunjeniZahtjevi

zahtjevi_PC <- data.frame(group = c("Ispunjeni zahtjevi", "Neispunjeni zahtjevi"),
                          value = c(nrow(ispunjeniZahtjevi), nrow(neispunjeniZahtjevi)))
zahtjevi_PC

ggplot(zahtjevi_PC, aes(x = "", y = value, fill = group)) + 
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(round(value/nrow(hotel), 2) * 100, "%")), position = position_stack(vjust = 0.5)) +
  labs(title = "Odnos ispunjenih i neispunjenih zahtjeva gostiju", x = NULL, y = NULL) + 
  scale_fill_brewer(palette = "Set2", name = "Vrsta zahtjeva")


# ggsave("../figures/najpopularnije_sobe.png")


```



#IVA
```{r}
hotel <- read_csv("../data/Hotel bookings/hotel_bookings.csv")
hotel
head(hotel, 15)

#Posjećenost kroz godine. Koja godina je najviša posjećenost? 

#datumi po godini 
table(hotel$arrival_date_year) 

#ne uzimamo u obzir one koji su otkazali
hotel_filtriran <- hotel %>% filter(is_canceled == 0)

#datumi po godini - hotel filtriran
table(hotel_filtriran$arrival_date_year)

#koristiti arrival_date_year (SORRY FILIP, IPAK TREBA!)
godisnja_statistika <- hotel_filtriran %>% group_by(arrival_date_year) %>% summarise(visits = n()) 


ggplot(godisnja_statistika, aes(x = as.factor(arrival_date_year), y = visits, fill = as.factor(arrival_date_year))) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Accent") +
  labs(title = "Godišnja posjećenost",
       x = "Godina",
       y = "Broj posjeta") +
  theme_minimal() +
  guides(fill = guide_legend(title = "Godine"))



#Koje godine je bilo najvise otkazanih rezervacija?
otkazane_rezevracije <- table(hotel$arrival_date_year) - table(hotel_filtriran$arrival_date_year)
otkazane_rezervacije_df <- data.frame(godina = names(otkazane_rezevracije), otkazane_rezevracije = as.numeric(otkazane_rezevracije))
otkazane_rezervacije_df

ggplot(otkazane_rezervacije_df, aes(x = godina, y = otkazane_rezevracije, fill = godina)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Paired") +
  labs(title = "Broj otkazanih rezervacija na godišnjoj razini",
       x = "",
       y = "Broj otkazanih rezervacija") +
  theme_minimal() + 
  guides(fill = guide_legend(title = "Godine"))

#Istraživanje sezonskih varijacija u rezervacijama tijekom godine. (Kroz jednu najpopularniju i najnepopularniju godinu statistika po mjesecima.)

#Izdvajanje godine i mjeseca
hotel_filtriran
hotel_godisnje_doba <- hotel_filtriran %>%  
  mutate(godisnje_doba = case_when(arrival_date_month %in% 3:5 ~ "Proljeće",
                                   arrival_date_month %in% 6:8 ~ "Ljeto",
                                   arrival_date_month %in% 9:11 ~ "Jesen",
                                   TRUE ~ "Zima"))

# Filtriranje podataka za najpopularniju i najmanje popularnu godinu
najpopularnija_godina <- hotel_godisnje_doba %>%
  group_by(arrival_date_year) %>%
  summarise(broj_rezervacija = n()) %>%
  filter(broj_rezervacija == max(broj_rezervacija)) %>%
  pull(arrival_date_year)

najnepopularnija_godina <- hotel_godisnje_doba %>%
  group_by(arrival_date_year) %>%
  summarise(broj_rezervacija = n()) %>%
  filter(broj_rezervacija == min(broj_rezervacija)) %>%
  pull(arrival_date_year)

# Filtrirajte podatke za najpopularniju godinu
najpopularnija_godisnja_statistika <- hotel_godisnje_doba %>%
  filter(arrival_date_year == najpopularnija_godina)

# Filtrirajte podatke za najnepopularniju godinu
najnepopularnija_godisnja_statistika <- hotel_godisnje_doba %>%
  filter(arrival_date_year == najnepopularnija_godina)


# ggplot  za najpopularniju godinu
ggplot(najpopularnija_godisnja_statistika, aes(x = arrival_date_month, fill = godisnje_doba)) +
  geom_bar(position = "stack") +
  labs(title = paste("Sezonske varijacije u najpopularnijoj godini:", najpopularnija_godina),
       x = "Mjesec",
       y = "Broj rezervacija") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() + 
  guides(fill = guide_legend(title = "Godišnje doba"))

# ggplot  za najpopularniju godinu
ggplot(najnepopularnija_godisnja_statistika, aes(x = arrival_date_month, fill = godisnje_doba)) +
  geom_bar(position = "stack") +
  labs(title = paste("Sezonske varijacije u najnepopularnijoj godini:", najnepopularnija_godina),
       x = "Mjesec",
       y = "Broj rezervacija") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() + 
   guides(fill = guide_legend(title = "Godišnje doba"))


#Iz koje države dolazi najviše gostiju po godine? --FIX THIS, NOW WORKING
# top 10 država prema broju posjetitelja
top_countries <- hotel_filtriran
  group_by(country) %>%
  summarise(visit_count = n()) %>%
  top_n(10, wt = visit_count)

ggplot(top_countries, aes(x = fct_reorder(country, visit_count), y = visit_count, fill = country)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 10 Visitor Countries",
       x = "Country",
       y = "Number of Visitors") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()






```


